<?php
/*
 * Functions file
 * Includes all necesary files
 * PLEASE DO NOT EDIT THIS FILE IN ANY WAY
 *
 * @package parabola
 */

// variable for theme version
define ("PARABOLA_VERSION","0.9.7.3");

require_once(dirname(__FILE__) . "/admin/main.php"); // Load necessary admin files

//Loading include files
require_once(dirname(__FILE__) . "/includes/theme-setup.php"); //Setup and init theme
require_once(dirname(__FILE__) . "/includes/theme-styles.php"); //Register and enqeue css styles and scripts
require_once(dirname(__FILE__) . "/includes/theme-loop.php"); //Loop related fiels
require_once(dirname(__FILE__) . "/includes/theme-meta.php"); //Meta related fiels
require_once(dirname(__FILE__) . "/includes/theme-frontpage.php"); //Frontpage generation
require_once(dirname(__FILE__) . "/includes/theme-comments.php"); //Theme comment functions
require_once(dirname(__FILE__) . "/includes/theme-functions.php"); //Theme misc functions
require_once(dirname(__FILE__) . "/includes/theme-hooks.php"); //Theme hooks

?>